### ISSUE TITLE
Selecting multiple elements for grouping

### ISSUE THREAD

**Issue by larpon** [aibosan/anigen#8]
Thanks for this awesome project.

I can't find any way to select multiple elements - and make a group of these?

**Comment by aibosan** [comment]
Thanks for the input, and your interest.

There's currently no way to select multiple elements. However, there is a workaround. You _can_ create a group around a single selected element (ctrl+g or object->group). While somewhat more time-consuming, you can then cut (ctrl+x) another element, select the new group, and paste it in place (ctrl+shitf+v).

That probably seems really weird, but I find multi-select doesn't gel well with one of the main design philosophies - manipulating individual elements with the clarity of the underlying XML in mind. The way things are set up, each time I started building a multi-select system, I just started running into dozens of weirdly specific scenarios which made the behavior vastly different from manipulating a single element, which is never good.

How do you treat pasting animations into elements which cannot display them? How do you treat pasting transformation animations into elements which are nested? How about if some of the elements are animations (which would normally replace their timing) and others are regular elements?

As a result, the whole issue is now a really low priority, but I might get to tackle it eventually.

**Comment by larpon** [comment]
Alright - thanks for the explanation and workaround!
